name: sublette

on: push

jobs:
  assets:
    name: Assets
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Requirements
      run:  pip install -r factory/requirements.txt

    - name: Clear
      run:  rm -rf plates/* showcase/* configs/*

    - name: Generate
      run: |
        python factory/plates.py
        python factory/codesnippets.py
        python factory/kitsch.py
        python factory/configs.py

    - name: Commit
      uses: EndBug/add-and-commit@v7
      with:
        add: plates/* showcase/* configs/*
        message: 'Generate assets in GitHub Actions [ci skip]'
        pull_strategy: NO-PULL
